### ISSUE TITLE
cannot process Chinese characters

### ISSUE THREAD

**Issue by gfctam** [federicodotta/Brida#100]
I got below errors when I was playing with brida plugin with chinese character contains in the request.

![image](https://user-images.githubusercontent.com/29703732/168548201-ac0bd572-4f13-4b0a-ac17-275ca455f9c3.png)

Is anyone have experience with this issue so far and may be have some clues how to fix this issue?

Thanks

**Comment by federicodotta** [comment]
Hi @gfctam 

It is better to avoid to pass non UTF-8 chars back and forth using Pyro.

My advice is to encode/decode them using Base64 or ASCII-HEX. Brida offers all the necessary functions. When you create a plugin, you can decode/encode input/output to/from your Frida hooks using graphical buttons. On your JS code you have to encode/decode input/output using the same algorithm, using NodeJS dedicated functions or native ones from the platform you are working on.

Federico
