### ISSUE TITLE
to add -D flag to choose device while calling frida

### ISSUE THREAD

**Issue by mustafairan** [federicodotta/Brida#102]
Hi,

I m using multiple devices at the same time. So brida cant chose which one to hook (it uses the first device attached). Could you add a textbox to specify device id and call frida with -D deviceid. I m not sure how pyro work, so it might need some testing in terms of stability.

Regards

**Comment by federicodotta** [comment]
Hi @mustafairan,

I just added "Device ID" connection mode (and also Host:IP one). You can find those feature in the last build ([0.6pre](https://github.com/federicodotta/Brida/releases)).

Sorry for the big delay but I was busy on other projects.

Please let me know if the release solve your problem.

Federico

**Comment by mustafairan** [comment]
Hi @federicodotta 
Thanks for the support. I will try when I have time( it might take long time :))

**Comment by federicodotta** [comment]
Hi @mustafairan,

Yes, no problem! I understand!

Yes, you are right. Maybe I will send the actual pre-release because it may take some time before version 0.6.

Thanks,
Federico
