### ISSUE TITLE
Brida 0.5 - Exception with attach application

### ISSUE THREAD

**Issue by bigrob69** [federicodotta/Brida#103]
Hello

Getting the exact same issue as #65  albeit on version 0.5 and not 0.4

Windows 10
Burp 2022.3.8
Brida 0.5
frida-compile 9.5.2 and 10.2.5 (both tested)
res files from "Load functionality" and commit 
https://github.com/federicodotta/Brida/commit/21ec48ff43bcdc621e40f3782b1298a76310fb58  (both tested)
"Use old Frida" selected and not selected.  (both tested)
Same error regardless of combinations above - attempting both spawn and attach
![brida_error](https://user-images.githubusercontent.com/16771620/170438430-8a2d43b1-7f50-4877-a252-7a846a5af542.PNG)

**Comment by federicodotta** [comment]
Hi @bigrob69 

Usually you have that error when Brida can't find JS files it needs.

You first created default JS files using the "Create default JS files" button?

Federico

**Comment by bigrob69** [comment]
Hello @federicodotta 

Yes, I have used the  "Create default JS files" button.  The "Frida JS files folder" is set to the directory where the files were created, however, the error persists.

regards
Rob

**Comment by federicodotta** [comment]
Hello @bigrob69,

Sorry for the delay in the response. I was quite busy on other projects. 

Can you please try with the last release I put on GitHub (0.6pre). There is a fix for a compatibility issue between frida-compile >= 10 and Brida. Now Brida should work well with frida-compile >= 0. 

Thanks,
Federico
