### ISSUE TITLE
 Is there any API in Brida?

### ISSUE THREAD

**Issue by feifeider** [federicodotta/Brida#104]
Hello，@federicodotta
     Is there any API in Brida can i use to process applications’ own methods?
Thanks!

**Comment by federicodotta** [comment]
Hi @feifeider,

Sorry for the delay in the response. I was quite busy on other projects.

I have not understood your question. Brida uses Frida as engine and Frida can add hooks on any application own method. Within Brida you can create custom Frida JS code and call it from Burp Suite, using the custom plugin engine of Brida. You can add as an example a plugin that execute an application own method on a portion of each request or response (to handle encryption or signature).

Federico
