### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by william1042** [federicodotta/Brida#110]
<img width="1260" alt="image" src="https://github.com/federicodotta/Brida/assets/22214530/728f9b13-76ed-477f-be9a-c548abfa76ea">

**Comment by federicodotta** [comment]
Hi @william1042,

The issue is caused by the fact that frida-compile does not find NodeJS.

If you are using a MacOS, refer to the Troubleshooting page of [Brida wiki](https://github.com/federicodotta/Brida/wiki/Troubleshooting) for details on how to fix your issue.

Federico
