### ISSUE TITLE
error: unknown option '-x'

### ISSUE THREAD

**Issue by aannjjiill** [federicodotta/Brida#111]
Hi,

I'm getting this error every time I press on Attach or Spawn application:

![2023-07-16_20-55](https://github.com/federicodotta/Brida/assets/39268311/4e171635-3bed-48ad-90b8-9e92229d3765)

I tried running frida-compile.cmd manually without "-x "and got this error again: 
![image](https://github.com/federicodotta/Brida/assets/39268311/7cca0762-b016-452b-b212-a855a1b06110)
Anyone up with the fix?

Thanks
Anjil

**Comment by federicodotta** [comment]
Hi @aannjjiill,

Please try again with last pre-release I recently uploaded ([0.6pre](https://github.com/federicodotta/Brida/releases)). There is a fix for frida-compile >= 10. 

Please try Brida 0.6pre with a version of frida-compile equals to or greater than 10 without flagging the option "Use old version of frida-compile (<10)" and let me know if this fix your issue.

Federico

**Comment by aannjjiill** [comment]
Hi @federicodotta ,

Thank you for your quick reply. I tried as per the instruction but still getting these errors. May be the JS file path is incorrect? or maybe the frida-complie is not working right? 

![image](https://github.com/federicodotta/Brida/assets/39268311/f767a46a-0a54-4789-8ad8-87c60d645b45)

**Comment by aannjjiill** [comment]
And do I need to put any JS script in to my mobile device to run it? Fyi, I am using a physical rooted android device here.

**Comment by federicodotta** [comment]
Hi @aannjjiill,

Do you created the default JS files using the  "Create default JS files" button? This button creates JS files with Frida functions used by Brida (and automatically set the right path in the "Frida JS files folder" field). You always need to start from Brida default JS files because they contain code needed for Brida working. You can then add your own scripts in the brida.js file.

Federico

**Comment by JLPung** [comment]
Hi, I am new to brida. I am also facing this issue. 

Have followed the following steps to install: 
1. Install pyro4
2. Install frida-compile version as advised. 
3. Created the default JS files using create default JS files button and saved them in My Documents folder. 

Am getting this following error: 

![image](https://github.com/federicodotta/Brida/assets/59461655/2859bf43-1717-457f-9795-823f591a46e8)

**Comment by federicodotta** [comment]
Hi @JLPung,

You have to uncheck "Use old version of frida-compile". Refer to the Wiki for further details.

Federico

**Comment by clschao** [comment]
thanks，I have fixed the problem，use python3.9.12 and frida15.2.2，frida-compile@10.2.5 can worked
