### ISSUE TITLE
Exception with execute method

### ISSUE THREAD

**Issue by CHINA-china** [federicodotta/Brida#116]
Exception with execute method net.razorvine.pyro.PyroException: [frida.core.RPCException] unable to find method 'exportedfunction' net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2861) java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) java.base/java.lang.Thread.run(Thread.java:833)

brida.js
![image](https://github.com/federicodotta/Brida/assets/92798047/cfe76c07-0445-46f0-8a83-ac2e63f275a4)

**Comment by federicodotta** [comment]
Hi @CHINA-china,

Can you give me more details? Brida has been properly configured? For more details on Brida configurations refer to the following documentation page: https://github.com/federicodotta/Brida/wiki/Start

Federico

**Comment by zangcc** [comment]
@CHINA-china 老哥，我最近也在用Brida，还剩最后一个问题一直解决不了，想请教一下你Spawn application，收到能回复一下吗，万分感谢！！🙏🙏🙏

**Comment by CHINA-china** [comment]
> @CHINA-china老哥，我最近一直在用Brida，还剩下最后一个问题一直解决不了，想请教一下你的Spawn申请，收到能回复一下吗，万分感谢！！🙏🙏🙏
我用的不是Spawn application，这个插件6.0版本生产的js文件没办法使用，你的使用5.0版本生产js文件，给6.0用，但是好像这样不能return值，并且不能传参数

**Comment by CHINA-china** [comment]
> @CHINA-china老哥，我最近一直在用Brida，还剩下最后一个问题一直解决不了，想请教一下你的Spawn申请，收到能回复一下吗，万分感谢！！🙏🙏🙏
我用的不是Spawn application，这个插件6.0版本生产的js文件没办法使用，你的使用5.0版本生产js文件，给6.0用，但是好像这样不能return值，并且不能传参数

**Comment by CHINA-china** [comment]
@federicodotta I am using the window system, frida is 16.1.3, frida compile.exe is 16.1.3, and brida is 6.0. I found that using the js script file produced by brida 6.0 cannot hook properly. The program will prompt "Exception with execute method net. razorvine. pyro. PyroException: [frida. core. RPCException] cannot find method 'getplatform'", and any custom rpc exports cannot be found. Brida6.0 uses JavaScript files produced by Brida5.0 or uses Birda5.0 to hook programs, but cannot pass in parameters or return values.

**Comment by CHINA-china** [comment]
brida0.5 Can operate normally, but cannot pass parameters and return values
![image](https://github.com/federicodotta/Brida/assets/92798047/4ff7b136-23da-4896-aace-aab6a748c3df)
![image](https://github.com/federicodotta/Brida/assets/92798047/3a42a2e1-83a1-4a3d-9313-acd22f43d4eb)
![image](https://github.com/federicodotta/Brida/assets/92798047/42779fb5-f403-4ee4-ac59-757f030dd2b1)
![image](https://github.com/federicodotta/Brida/assets/92798047/12bee82c-0de0-4d26-818d-42031c12050b)

brida0.6 Unable to run properly and customize rpc.exports
![image](https://github.com/federicodotta/Brida/assets/92798047/55907d94-f769-4922-a7f4-196d37ab855f)
![image](https://github.com/federicodotta/Brida/assets/92798047/10a9a83d-d971-44dc-94cc-953aae496876)
![image](https://github.com/federicodotta/Brida/assets/92798047/5ac8c952-3f88-4973-b8a8-a41979d875ba)
![%VIVQ1_GIS) Y3{5D64UEKC](https://github.com/federicodotta/Brida/assets/92798047/35825890-ea4f-4bf3-b572-5509c30a831f)

**Comment by federicodotta** [comment]
Hi @CHINA-china,

I made some checks and I found the issue. The problem is latest versions of frida-compile (v16.3.0). I tried with last version of Brida (0.6pre) and frida-compile (v16.3.0) and I have your same exception.

Then I tried with last version of Brida (0.6) and with frida-compile 10.2.5 and all works correctly. I try all the Brida functionality using the [supplied Android demo](https://github.com/federicodotta/Brida/tree/master/Demo/Android) without any issues.  

Can you please try again with Brida 0.6pre frida-compile 10.2.5? In the meanwhile I will try to understand what changed in frida-compile.

Thanks,
Federico

**Comment by CHINA-china** [comment]
Of course, thanks

**Comment by CHINA-china** [comment]
Can you tell me what version of Frida you are using? I found frida-compile version 10.2.5, but I couldn't find Frida version 10.2.5. I am using Python 3.7, frida-compile 10.2.5, frida 12.7.5, and Brida 0.6pre. I am getting the error "Exception with attach application net.razorvine.pyro.PyroException: [frida.InvalidArgumentError] gDBus.Error:re.frida.Error.InvalidArgument: Script(line 2497): SyntaxError: parse error."
Thanks
![image](https://github.com/federicodotta/Brida/assets/92798047/34fb2371-0ec4-42a0-9a5d-4d42b05866e4)

**Comment by federicodotta** [comment]
HI @CHINA-china,

I was using the 15.2.1 version of Frida but your error seems to be a compilation error. I don't think that it depends on the Frida version.

Did you recompile the JS files after changing version of frida-compile? You can recompile files using the "Compile&Spawn" and "Compile&Attach" buttons.

Federico

**Comment by zangcc** [comment]
@federicodotta Hello author, I used Brida 6 according to your configuration requirements, frida-compile:10.2.5, Frida-server:15.0.0-android-arm64, Frida15.0.0. The service can be started normally, as shown in the following figure:
![image](https://github.com/federicodotta/Brida/assets/64825932/12025554-552f-4b59-a6cd-0e17307cecfd)

But when using the "Debug export" function, I encountered the same problem, that is, an error was reported: Exception with execute method net.razorvine.pyro.PyroException: [frida.core.RPCException] unable to find method 'test'.
![image](https://github.com/federicodotta/Brida/assets/64825932/fe01aabc-8f1d-4d8f-9e20-b4b6d19a501e)
![image](https://github.com/federicodotta/Brida/assets/64825932/2b78b621-2d33-43af-8f94-77b491611b87)
Exception with execute method net.razorvine.pyro.PyroException: [frida.core.RPCException] unable to find method 'test' net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2862) java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) java.base/java.lang.Thread.run(Thread.java:833)

I hope you can help me find the cause of the problem as soon as possible, thank you~

@CHINA-china 大佬，我也遇到了这个问题，请问你最后解决了吗？Debug export一直报错，希望可以留个联系大家互相讨论一下，或者可以加我v:5b6u5L+h5Y+377yaemFuZ2NjZGRkZA==，真的很需要尽快解决这个brida的问题，谢谢了~
