### ISSUE TITLE
Entrypoint must be inside the project root (ERROR)

### ISSUE THREAD

**Issue by S3ntago** [federicodotta/Brida#119]
Hi, 

I'm facing an issue with setting the path of "Firda JS Files Folder", I'm not sure where do I get this path, and while I'm trying to attach application, I get the below errors:
![image](https://github.com/federicodotta/Brida/assets/48615614/b6a6b522-43dc-44c5-91cf-736c9a33c2d4)

**Comment by sven-crayon** [comment]
@S3ntago  how did you resolve this issue?

**Comment by sushi2k** [comment]
@S3ntago  how did you resolve this issue?
