### ISSUE TITLE
Exception starting Pyro server

### ISSUE THREAD

**Issue by GHXST01** [federicodotta/Brida#12]
Burp Suite is being started with administrative rights on my Windows 10 machine.
The following error occurs when starting the server.

```java.io.IOException: Cannot run program "C:\Python\": CreateProcess error=5, Access is denied java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) java.lang.Runtime.exec(Runtime.java:620) java.lang.Runtime.exec(Runtime.java:485) burp.BurpExtender.launchPyroServer(BurpExtender.java:899) burp.BurpExtender.actionPerformed(BurpExtender.java:1367) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6533) javax.swing.JComponent.processMouseEvent(JComponent.java:3324) java.awt.Component.processEvent(Component.java:6298) java.awt.Container.processEvent(Container.java:2236) java.awt.Component.dispatchEventImpl(Component.java:4889) java.awt.Container.dispatchEventImpl(Container.java:2294) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) java.awt.Container.dispatchEventImpl(Container.java:2280) java.awt.Window.dispatchEventImpl(Window.java:2746) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) java.awt.EventQueue.access$500(EventQueue.java:97) java.awt.EventQueue$3.run(EventQueue.java:709) java.awt.EventQueue$3.run(EventQueue.java:703) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) java.awt.EventQueue$4.run(EventQueue.java:731) java.awt.EventQueue$4.run(EventQueue.java:729) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.awt.EventQueue.dispatchEvent(EventQueue.java:728) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by federicodotta** [comment]
Hi! From the error it seems that you insert Python folder and not python binary in Brida configuration. You have to insert for example:

`C:\python27\python.exe`

It is not necessary to start Burp Suite with administrative rights.

Federico

**Comment by kaleemshaik7867** [comment]
@federicodotta I am also facing the same Issue. I am using Mac 

Here is the console log 

 Exception starting Pyro 
server java.util.concurrent.TimeoutException java.util.concurrent.FutureTask.get(FutureTask.java:205) burp.BurpExtender.launchPyroServer(BurpExtender.java:914) burp.BurpExtender.actionPerformed(BurpExtender.java:1367) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6533) javax.swing.JComponent.processMouseEvent(JComponent.java:3324) java.awt.Component.processEvent(Component.java:6298) java.awt.Container.processEvent(Container.java:2236) java.awt.Component.dispatchEventImpl(Component.java:4889) java.awt.Container.dispatchEventImpl(Container.java:2294) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) java.awt.Container.dispatchEventImpl(Container.java:2280) java.awt.Window.dispatchEventImpl(Window.java:2746) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) java.awt.EventQueue.access$500(EventQueue.java:97) java.awt.EventQueue$3.run(EventQueue.java:709) java.awt.EventQueue$3.run(EventQueue.java:703) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) java.awt.EventQueue$4.run(EventQueue.java:731) java.awt.EventQueue$4.run(EventQueue.java:729) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.awt.EventQueue.dispatchEvent(EventQueue.java:728) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kaleemshaik7867** [comment]
![image](https://user-images.githubusercontent.com/7692857/42137542-0edc0290-7d7f-11e8-82c1-ba8d91362b27.png)

**Comment by kaleemshaik7867** [comment]
Yes

**Comment by federicodotta** [comment]
Hi kaleemshaik7867! Your problem is different from GHXST01 problem.

Have you installed all Brida dependencies? Have you started frida-server on your mobile device?

Unfortunately at the moment it is difficult to debug starting problem but I'm working on it and soon I will release a new version of Brida with more verbose starting errors.

**Comment by federicodotta** [comment]
Hi kaleemshaik7867! On the BAppStore there was a wrong (old) version of Brida. Now there is the correct one. Please try to remove and re-download Brida from BAppStore. Then remember that you have to use Brida JS file (obviously you can add your hooks and exports to that file, but Brida needs specific JS functions contained in that file).

Let me know if this solve your problem.

Federico

**Comment by federicodotta** [comment]
Hi! I just release a new version of Brida (0.3) more verbose with errors when starting Pyro server. Let me know if with this version you can get more details on your problem.

**Comment by blshkv** [comment]
The problem seems with /tmp/bridaServicePyro.py as it does not support python3
The workaround is to specify /usr/bin/python2 in the configuration

**Comment by PenOps** [comment]
I had the same problem and found a way to fix it.

Let's assume your Python binary path in Frida is **/usr/local/bin/python2.7**
Type the following in bash:
`/usr/local/bin/python2.7 -m pip install frida pyro4`

**Comment by PenOps** [comment]
I had the same problem and found a way to fix it.

When you do `pip install frida pyro4` or `pip3 install frida pyro4` you will get the message that it's already installed.

Let's assume your Python binary path in Frida is **/usr/local/bin/python2.7**
Type the following in bash:
`/usr/local/bin/python2.7 -m pip install frida pyro4`

After that, it works like a charm :-)

**Comment by blshkv** [comment]
Is it fixed?

**Comment by federicodotta** [comment]
Hi blshkv,

Brida 0.3 supports only Python 2. I made a lot of changes to Brida that I will publish for HackInParis 2020. Meanwhile you can find a fix for Python 3 here:

https://github.com/federicodotta/Brida/issues/39#issuecomment-596064419

Federico

**Comment by blshkv** [comment]
can you push the patch to the git please? This way is easier to test it.

**Comment by federicodotta** [comment]
Fixed with Brida 0.4
