### ISSUE TITLE
Bad video link in BApp description

### ISSUE THREAD

**Issue by raulsiles** [federicodotta/Brida#13]
The video link at BApp points to the PDF too :)
https://portswigger.net/bappstore/2c0def96c5d44e159151b236de766892

**Comment by federicodotta** [comment]
Hi raulsiles, thank you for the report. I reported the issue to Burp Suite team.

Federico

**Comment by federicodotta** [comment]
Fixed! Thank you!

**Comment by raulsiles** [comment]
Great! :-)
