### ISSUE TITLE
Cannot use arguments in Execute Method

### ISSUE THREAD

**Issue by SaneBow** [federicodotta/Brida#16]
When I tried to use execute method tab, I found that the method cannot receive the arguments. I used following simple test case to produce the issue.
```javascript
rpc.exports = {
	dummytest: function(s) {
		console.log('param:', s);
		return s;
}
```
In `Execute method` tab, I input `dummytest` as method name and add `test` to argument list.

This is the output:

```
Reloading script executed  
param: 
*** Output dummytest:
```

You can see that although the method was executed, it didn't get the argument.

Did I do anything wrong?

Additional info:
- Brida version: 0.2
- Frida version: 11.0.3

**Comment by federicodotta** [comment]
Hi! After writing the argument, do you have clicked on the "Add" button? Because otherwise it does not take the argument.

**Comment by SaneBow** [comment]
I did. I am sure because it was shown in the "argument list". 

Anyway, when I tried it again today on a different machine, it worked. I will close this issue for now and maybe reopen it later if I can reproduce the bug.

Thanks.
