### ISSUE TITLE
Exception with getting info Android/iOS

### ISSUE THREAD

**Issue by some1russian** [federicodotta/Brida#18]
Hello there 
I have a rooted android device,followed the installation guide 
but i have these exceptions 

`Exception with getting info Android/iOS net.razorvine.pyro.PyroException: [frida.core.RPCException] unable to find method 'getplatform' net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender.actionPerformed(BurpExtender.java:1265) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6533) javax.swing.JComponent.processMouseEvent(JComponent.java:3324) java.awt.Component.processEvent(Component.java:6298) java.awt.Container.processEvent(Container.java:2236) java.awt.Component.dispatchEventImpl(Component.java:4889) java.awt.Container.dispatchEventImpl(Container.java:2294) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) java.awt.Container.dispatchEventImpl(Container.java:2280) java.awt.Window.dispatchEventImpl(Window.java:2746) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) java.awt.EventQueue.access$500(EventQueue.java:97) java.awt.EventQueue$3.run(EventQueue.java:709) java.awt.EventQueue$3.run(EventQueue.java:703) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) java.awt.EventQueue$4.run(EventQueue.java:731) java.awt.EventQueue$4.run(EventQueue.java:729) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.awt.EventQueue.dispatchEvent(EventQueue.java:728) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) java.awt.EventDispatchThread.run(EventDispatchThread.java:82) `

**Comment by federicodotta** [comment]
Hi! Are you using JS file supplied with Brida? Because it contains functions like "getplatform" that are used by the plugin.

**Comment by lukaszbobrek** [comment]
@some1russian can you share release of your build?
I am facing exactly the same problem.

**Comment by some1russian** [comment]
yup i use the JS file,the latest one ...

**Comment by federicodotta** [comment]
Hi! I just release a new version of Brida (0.3) in which you can load default JS file directly from Brida configuration pane. Let me know if you can fix your problem.

**Comment by liberatorqjw** [comment]
i use the Brida(0.3), and use the default js File . also have the error.

**Comment by pygain11** [comment]
net.razorvine.pyro.PyroException: [frida.core.RPCException] VM::GetEnv failed: -2

**Comment by abdilahrf** [comment]
got the same issue in latest version brida

**Comment by federicodotta** [comment]
The getPlatform method is defined in the default JS file supplied with Brida. You can download and use this file clicking on the "Load default JS file" button on the left of the "Frida JS file path" line. It is necessary to add your own methods to my JS file, because it contains Frida hooks used by Brida

**Comment by abdilahrf** [comment]
@federicodotta I already did that, and still same

**Comment by zangcc** [comment]
Hello~ In the latest version of Brida, this issue still exists. JS files are automatically provided. Confirm the existence of the JS files, but still prompt Exception with getting information for Android/iOS. @federicodotta 

<img width="1097" alt="image" src="https://github.com/federicodotta/Brida/assets/64825932/811b1a04-f440-4029-b336-330b81dd6139">

**Comment by c0g4ih4l4n** [comment]
I have the same problem, do you able to solve it yet @zangcc ?

**Comment by zangcc** [comment]
Hello my friend, yes I have solved it. First, you need to click "Reload JS", then click "Compile&reload JS", which requires 2 or more back and forth times. I personally tested it and this method can be solved! @c0g4ih4l4n

**Comment by yiqunlan** [comment]
Hi, for those who encountered this issue recently, you can solve this problem by downgrading frida-compile to 10.2.5. 
Download by using npm:
`npm install frida-compile@10.2.5`
Then grab the binary to your brida configration page, which should be located at:
`<INSTALLED_DIRECTORY>/node_modules/.bin/frida-compile`
Remeber recompile your js script
<img width="542" alt="image" src="https://github.com/federicodotta/Brida/assets/86314033/a3b13e0d-b1a1-4dc0-b2a8-387deb6b88cd">
