### ISSUE TITLE
problem in starting Pyro server

### ISSUE THREAD

**Issue by manish199014** [federicodotta/Brida#19]
Hello, 
I am using Brida on MacOS and burp suite pro version. I am getting the below error on running brida server. Could you please help me to resolve this? 

<img width="868" alt="screen shot 2018-07-10 at 6 23 23 pm" src="https://user-images.githubusercontent.com/14213944/42511204-d2848e9c-846e-11e8-9192-8fbaebaa0dab.png">

Exception starting Pyro server java.util.concurrent.TimeoutException java.util.concurrent.FutureTask.get(FutureTask.java:205) burp.BurpExtender.launchPyroServer(BurpExtender.java:914) burp.BurpExtender.actionPerformed(BurpExtender.java:1367) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6533) javax.swing.JComponent.processMouseEvent(JComponent.java:3324) java.awt.Component.processEvent(Component.java:6298) java.awt.Container.processEvent(Container.java:2236) java.awt.Component.dispatchEventImpl(Component.java:4889) java.awt.Container.dispatchEventImpl(Container.java:2294) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) java.awt.Container.dispatchEventImpl(Container.java:2280) java.awt.Window.dispatchEventImpl(Window.java:2746) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) java.awt.EventQueue.access$500(EventQueue.java:97) java.awt.EventQueue$3.run(EventQueue.java:709) java.awt.EventQueue$3.run(EventQueue.java:703) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) java.awt.EventQueue$4.run(EventQueue.java:731) java.awt.EventQueue$4.run(EventQueue.java:729) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.awt.EventQueue.dispatchEvent(EventQueue.java:728) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) java.awt.EventDispatchThread.run(EventDispatchThread.java:82)  

OS Details: Darwin Manish.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by 0x7678** [comment]
Same problem here :(

**Comment by Loris1123** [comment]
I'm having the same issue under ArchLinux.
What I've tried so far:
- Using Python 3 and Python 2
- Using Virtualenv and System-Python
- Installing Brida from BApp Store and install manually

**Comment by Loris1123** [comment]
I just just able to launch the pyro server. Appearently there is a problem with frida in a virtualenv. When I wrote above I tried  to use System-Python, I actually only installed Pyro4 in my system's python environment. Frida was still in a virtualenv.

When I installed both, frida and Pyro4 in my system's Python2.7 library, the server started immediately.

**Comment by d3vilbug** [comment]
same problem 

java.util.concurrent.TimeoutException java.util.concurrent.FutureTask.get(FutureTask.java:201) burp.BurpExtender.launchPyroServer(BurpExtender.java:914) burp.BurpExtender.actionPerformed(BurpExtender.java:1367) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6516) javax.swing.JComponent.processMouseEvent(JComponent.java:3311) java.awt.Component.processEvent(Component.java:6281) java.awt.Container.processEvent(Container.java:2229) java.awt.Component.dispatchEventImpl(Component.java:4872) java.awt.Container.dispatchEventImpl(Container.java:2287) java.awt.Component.dispatchEvent(Component.java:4698) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422) java.awt.Container.dispatchEventImpl(Container.java:2273) java.awt.Window.dispatchEventImpl(Window.java:2719) java.awt.Component.dispatchEvent(Component.java:4698) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735) java.awt.EventQueue.access$200(EventQueue.java:103) java.awt.EventQueue$3.run(EventQueue.java:694) java.awt.EventQueue$3.run(EventQueue.java:692) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) java.awt.EventQueue$4.run(EventQueue.java:708) java.awt.EventQueue$4.run(EventQueue.java:706) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) java.awt.EventQueue.dispatchEvent(EventQueue.java:705) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by federicodotta** [comment]
Hi. I just release a new version of Brida (0.3) more verbose with errors starting Pyro4 server. Please try the new version and let me know if it gives you more details on your exceptions.

**Comment by d3vilbug** [comment]
Sure :)

**Comment by federicodotta** [comment]
Hi exrme18,

you have to install python Frida module (pip install Frida).

**Comment by exrme18** [comment]
@federicodotta 

It is already installed on my system.  

Requirement already satisfied: frida in /usr/local/lib/python2.7/site-packages (12.1.0)

Can you please help me to troubleshoot this?

Thanks

**Comment by d3vilbug** [comment]
Thanks @federicodotta  pyro server started but not able to pwned application as mentioned in "Spawn Application Error" issue thread

**Comment by dashmesh** [comment]
@exrme18,
you may have a local python2 install along with the system install.
In the Brida UI, put the python binary path as  "**usr/local/bin/python**". instead of "**/usr/bin/python**"
