### ISSUE TITLE
Execute Method not working

### ISSUE THREAD

**Issue by theblackturtle** [federicodotta/Brida#20]
Hi, I'm using Brida to hook Android app. 
After decrypt I have this code:
```
final String b() throws Exception {}
    .....
    return v0;

public final void b(Application arg6) {}
```
and this is my js function which is get String from b():
```
tokenfunc: function (a) {
    Java.perform(function () {
        var es_hook = Java.use("es");
        es_hook.b.overload().implementation = function () {
            var result = this.b();
            return result;
        };
    });
},
```
It's not work in Brida(Output always null), but when I use Frida, It's work fine. Please tell me why. Thanks.

**Comment by abdilahrf** [comment]
> rpc.exports = {
>   tokenfunc: function () {
>     Java.perform(function() {
>       var es_class = Java.use("es");
>       return es_class.b();
>     });
>   }
> }

@federicodotta we cannot export that function like that, the returned value is not correct 

```
rpc.exports = {
  tokenfunc: function () {
    Java.perform(function() {
     var es_class = Java.use("es");
     return es_class.b(); // this is not returned to the tokenfunc function
    });
  return "TEST" ; // this is what returned to tokenfunc function how we able to make the return to here
 }
}
```

**Comment by federicodotta** [comment]
Hi abdilahrf,

I think that your problem may be caused by the fact that Java.perform is potentially asynchronous. Please refer to [this frida issue](https://github.com/frida/frida/issues/380) and let me know if it solves your problem!

Federico
