### ISSUE TITLE
Spawn Application Error: iOS

### ISSUE THREAD

**Issue by PtolemyRE** [federicodotta/Brida#25]
Exception with spawn application net.razorvine.pyro.PyroException: [frida.NotSupportedError] unable to launch iOS app: The operation couldnât be completed. (FBSOpenApplicationErrorDomain error 1.) net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69)

Tried on an iOS 64 bit device to see if that was the issue and it crashes immediately.

Anyone have any ideas on what this could be?

My android setup works perfectly fine.

**Comment by federicodotta** [comment]
Hi! Did you try to spawn the app directly with Frida without Brida?
