### ISSUE TITLE
Supported Return types?

### ISSUE THREAD

**Issue by priyankn** [federicodotta/Brida#27]
Hey! 

I was curious as to how to handle return types which are not of the types String, Boolean or a pointer? (i.e. a custom type).

I see in the code that those are the only types supported for changing the return types of a method.

**Comment by federicodotta** [comment]
Hi, at the moment I implemented only those types. If you need different types you have to code a Frida hook inside you JS file. Unfortunately it is not simple to generalize custom data types...
