### ISSUE TITLE
What should I fill in the application ID if I wanna inspect some APP on MacOS[newest version]?

### ISSUE THREAD

**Issue by mr-m0nst3r** [federicodotta/Brida#29]
Can't find application ID for the app, I can get PID and full path such as `/Applications/HookMe.app`, but there seems no way to spawn that.

**Comment by federicodotta** [comment]
Hi mr-m0nst3r,

I never tried Brida with a MacOS app. It should work, but it is designed mainly to work with Android and iOS applications.

Next week I will try it with a MacOS application and I will let you know.

Federico

**Comment by federicodotta** [comment]
Hi Mr. Monster!

Excuse me, while working on new version of Brida I found a "lexical" bug in my code. In Brida 0.3 you have "Frida local" and "Frida remote". "Frida local" is USB mode and not local mode. For this reason you probably did not find a way to spawn MacOS app.

In the new version of Brida I fixed the lexical bug and I added the real Local mode. I will release the new version in June for HackInParis.

Meanwhile, you can work on MacOS apps by substituting "self.device = frida.get_usb_device()" to "self.device = frida.get_local_device()" in the res/bridaServicePyro.py file

Remember to rollback this fix if you need to analyze a USB application.

Federico

**Comment by federicodotta** [comment]
Hi @mr-m0nst3r,

please try again with the new version of Brida. Now the "local" option is correct.

Please re-open the bug if it is not fixed.

Have a nice day,
Federico
