### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by a2h4l2s4** [federicodotta/Brida#3]
Hello Researcher,
I'm just trying to add Brida in burp-suite as you say, but after downloading Brida in ZIP format I haven't found BridaXX.jar file anywhere in folder.  Pleas guide me through installation, I'm very excited to evaluate your cool invention

**Comment by inode-** [comment]
Hello,

you can download the compiled version of the project at the release page of github (https://github.com/federicodotta/Brida/releases).

Regards
