### ISSUE TITLE
Exception with spawn application net.razorvine.pyro.PyroException

### ISSUE THREAD

**Issue by kelvinBen** [federicodotta/Brida#35]
System Version: Mac OS

Mobile Version: iOS 11.2.6(jailbroken)

Python Version:2.7(Installed Pyro4)

Brida Version:

![image](https://user-images.githubusercontent.com/19259171/54070880-d0fdb800-42a0-11e9-8834-c5293c371af9.png)

Exception Info:

![image](https://user-images.githubusercontent.com/19259171/54070899-fab6df00-42a0-11e9-934f-64de0d02a7ce.png)

![image](https://user-images.githubusercontent.com/19259171/54070925-2c2faa80-42a1-11e9-9fa7-35304529191e.png)

**Comment by federicodotta** [comment]
Hi kelvinBen,

unfortunately I can't replicate your issue. Are you sure to have configured all the settings correctly?

Federico

**Comment by federicodotta** [comment]
Hi kelvinBen,

I released a new version of Brida that include a Wiki that explains how to configure the tool. Please try with the new version and reopen the issue if you have problems
