### ISSUE TITLE
iOS 12.0 cannot spawn

### ISSUE THREAD

**Issue by windyzxcui** [federicodotta/Brida#38]
iOS 12.0 cannot spawn

**Comment by oschvr** [comment]
https://github.com/federicodotta/Brida/issues/15#issuecomment-564122020

**Comment by federicodotta** [comment]
Hi windyzxcui,

I usually use Brida with a iOS 12 device and it works correctly. Can you supply more details?

Check also on the link supplied by oschvr. Maybe you are experiencing the same issue.

**Comment by federicodotta** [comment]
I close the issue. I try with different devices with iOS 12 and it works correctly. Furthermore, the new version of Brida supports also the "attach" mode. Please reopen the issue or open a new issue if you have further problems.
