### ISSUE TITLE
Cannot start pyro server

### ISSUE THREAD

**Issue by abdilahrf** [federicodotta/Brida#40]
I'm using Burp 2.1, cannot start the server its just looping null until my ram reach > 10gb 
i dont know why this is happening 

![image](https://user-images.githubusercontent.com/6015012/60765687-6894db00-a0c8-11e9-8956-5085dab882c7.png)

**Comment by federicodotta** [comment]
Hi!

It's a very strange behaviour. Have you double check if your Python path is correct and if you have installed Brida dependecies? (Pyro4,...)

**Comment by abdilahrf** [comment]
It seems my ptython2.7 is broken since deprecated.
