### ISSUE TITLE
Error during frida-compile. Aborting.

### ISSUE THREAD

**Issue by Rick11929** [federicodotta/Brida#47]
hi ，facing error on frida-compile path setting , how to set this one ?

![image](https://user-images.githubusercontent.com/12494183/79553181-ababc200-80ce-11ea-9a15-05056bfaa62b.png)

**Comment by federicodotta** [comment]
frida-compile requires nodejs to work. From the error it seems that the frida-compile executable could not find node binary. Have you tried to use frida-compile from command line? Is it working?

**Comment by Rick11929** [comment]
Hi，my frida-compile is working in my terminal 

![image](https://user-images.githubusercontent.com/12494183/79555824-c4b67200-80d2-11ea-83a9-dc0b8e75fe1d.png)

**Comment by Rick11929** [comment]
@federicodotta  ， Hi, thank you for your reply , the frida-compile command is working in my terminal 

➜  [/Users/isr] which frida-compile
/usr/local/bin/frida-compile
➜  [/Users/isr] frida-compile -h
Usage: frida-compile [options] <module>

Options:
  -V, --version             output the version number
  -o, --output <file>       set output <file>
  -w, --watch               watch for changes and recompile
  -b, --bytecode            output bytecode
  -x, --no-babelify         skip Babel transforms
  -X, --no-esmify           used with -x to also skip esmify transforms
  -L, --loose               enable loose Babel transformations
  -S, --no-sourcemap        omit sourcemap
  -c, --compress            compress using UglifyJS2
  -a, --use-absolute-paths  use absolute source paths
  -h, --help                output usage information

**Comment by federicodotta** [comment]
Please try the following command from the shell:
/usr/local/bin/frida-compile -x -o /Users/isr/Brida/res/bridaGeneratedCompiledOutput.js /Users/isr/Brida/res/brida.js

Is it working?

**Comment by Rick11929** [comment]
Hi， it's working 
![image](https://user-images.githubusercontent.com/12494183/79558844-65a72c00-80d7-11ea-9a14-4b2299c7a673.png)

**Comment by Rick11929** [comment]
@federicodotta ,hi , it's working
![image](https://user-images.githubusercontent.com/12494183/79559047-aef77b80-80d7-11ea-90f1-264ac1a1bc7a.png)

**Comment by federicodotta** [comment]
It seems to be a visibility problem of your node binary. From the error, Brida seems to execute the frida-compile binary, but the frida-compile binary seems unable to reach node binary. By googling there are many node users that suffer from the same issue. Maybe you can try to remove node and reinstall node from the official installer https://nodejs.org/en/download/

**Comment by Rick11929** [comment]
@federicodotta  , reinstall the node env and fix this issue , thx

**Comment by federicodotta** [comment]
Great!

@Rick11929 how do you fix the issue? Because another user on MacOS has the same issue and maybe your solution can help him.

Thank you,
Federico

**Comment by decart-hub** [comment]
Having the same issue... Tried reinstalling node, didn't help. If @Rick11929 can share his solution - would appreciate it. Will try the manual compile approach now..

**Comment by decart-hub** [comment]
> Please try the following command from the shell:
> /usr/local/bin/frida-compile -x -o /Users/isr/Brida/res/bridaGeneratedCompiledOutput.js /Users/isr/Brida/res/brida.js
> 
> Is it working?

That did the trick in my case. Thanks @federicodotta

**Comment by federicodotta** [comment]
Hi @decart-hub 

If you are working on a Mac you can try this:

https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/

Let me know if this solve your issue!

Federico

**Comment by 24h7d** [comment]
I have same problem, running with my linux. 
after installing frida-compile with npm command, I try running it. in Burp, starting server is OK then that error come up.

I try which frida-compile
frida-compile not found

how can we fix this?
thanks

**Comment by Sahabalam** [comment]
> I have same problem, running with my linux. after installing frida-compile with npm command, I try running it. in Burp, starting server is OK then that error come up.
> 
> I try which frida-compile frida-compile not found
> 
> how can we fix this? that

**Comment by Sahabalam** [comment]
sudo apt-get install npm
sudo npm install -g frida-complile

try this

**Comment by iamvinny** [comment]
I have a problem where the `bridaGeneratedCompiledOutput.js` file is not being generated, only the files below.

![Screenshot 2024-03-29 at 4 11 59 PM](https://github.com/federicodotta/Brida/assets/29668752/3e3da559-d4d0-4d7c-b635-73ea7df0ebe3)

And this is the error
```
env: node: No such file or directory

Error during frida-compile, potentially caused by compilation errors. Aborting. If exception details are not returned, try to run frida-compile manually. frida-compile command:

"/opt/homebrew/bin/frida-compile" -x -o "/Users/vinny/Documents/BridaFiles/bridaGeneratedCompiledOutput.js" "/Users/vinny/Documents/BridaFiles/brida.js"
```
