### ISSUE TITLE
frida-compile Running error

### ISSUE THREAD

**Issue by CTF-MissFeng** [federicodotta/Brida#49]
**Macos Brida running error：**

Exception during frida-compile java.io.IOException: Cannot run program "/usr/local/bin/": error=13, Permission denied java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) java.lang.Runtime.exec(Runtime.java:620) java.lang.Runtime.exec(Runtime.java:485) burp.BurpExtender.compileFridaCode(BurpExtender.java:2319) burp.BurpExtender.actionPerformed(BurpExtender.java:2885) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)

frida-compile normal operation：

![image](https://user-images.githubusercontent.com/38177965/80176836-6fc3b000-862c-11ea-97f8-2bf9c410f68a.png)

**Comment by federicodotta** [comment]
Hi,

in the configuration tab you have to put in the "frida-compile path" the full path of the **binary** of frida-compile. It seems from your error that you put "/usr/local/bin/" in that field
