### ISSUE TITLE
Brida.jar file not found 

### ISSUE THREAD

**Issue by naveen12** [federicodotta/Brida#5]
Hi, i read the article in https://www.reddit.com/r/netsec/ 
but while searching the brida.jar file in downloaded zip not found. can you please provide it.

**Comment by federicodotta** [comment]
Hi. Brida.jar is the compiled archive. In GitHub in the downloaded zip you have the sources and not the binaries. You can download the brida.jar archive in the "Release" page of the project:
https://github.com/federicodotta/Brida/releases

**Comment by naveen12** [comment]
thank you
