### ISSUE TITLE
load frida-compile path error，Permission denied.

### ISSUE THREAD

**Issue by Neo01010** [federicodotta/Brida#51]
![image](https://user-images.githubusercontent.com/15312660/80303281-c7efe300-87e1-11ea-9454-b175ce2ebd13.png)
![image](https://user-images.githubusercontent.com/15312660/80303288-d8a05900-87e1-11ea-801b-b026716309d3.png)

**Comment by Neo01010** [comment]
Mine workspace is Macos .

**Comment by Neo01010** [comment]
Mine workspace is Macos .

**Comment by federicodotta** [comment]
In frida-compile path you have to put the full path of frida-compile binary, not of frida-compile folder (example /usr/local/bin/frida-compile)

**Comment by Neo01010** [comment]
OK,thankx.I'm gonna try it.
