### ISSUE TITLE
Error When Spawning the application

### ISSUE THREAD

**Issue by mastercho** [federicodotta/Brida#55]
``Exception with spawn application net.razorvine.pyro.PyroException: [frida.ExecutableNotFoundError] unable to find executable at 'com.google.android.GoogleCamera' net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2714) java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) java.util.concurrent.FutureTask.run(Unknown Source) java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) java.lang.Thread.run(Unknown Source) ``

Doesn't matter what i try to spawn im getting same error

![](https://i.gyazo.com/78af9b679cfa56df17b5fc5e235ddd84.png)

**Comment by federicodotta** [comment]
Hi,

you choose "Frida Local" to spawn an Android process. You should use "Frida USB" if you are using an USB connected device or "Frida remote" if you are using port redirection.

Federico

**Comment by mastercho** [comment]
solved
