### ISSUE TITLE
Feature request: Support python virtualenv

### ISSUE THREAD

**Issue by floyd-fuh** [federicodotta/Brida#56]
I would really love to try Brida, but I simply can't install python packages in the main python installation. I know a lot of people do, but I've been in python-dependency-hell before and I never want to go back. Especially as this is very true for all the security people, because the different crypto packages in python2 used to conflict. Additionally, with frida it is again especially important to have virtualenvs. I have several phones, with different iOS/Android versions and they all have running frida hook scripts, but unfortunately with different frida versions. As you know frida versions on mobile devices and on the host have to match, otherwise you could run into arbitrary issues in my experience. Now with virtualenv I have all these problems solved, I simply never do a pip install directly and can have different frida versions in different virtualenvs. First create a virtualenv (sorry if you already know but I want it to make it as easy as possible for you to try):

```
$ virtualenv -p python3.7 myproject-virtualenv37
```

Afterwards I can activate it and install things in it:
```
$ source myproject-virtualenv37/bin/activate
myproject-virtualenv37 $ pip3 install frida
```

Then, when I use frida, I do:
```
$ source myproject-virtualenv37/bin/activate
myproject-virtualenv37 $ frida-trace
```

However, I can't activate that virtualenv in Brida. It would be nice if there would be a way to activate it.

I tried getting it to work by specifying the virtualenv python binary in Brida, which should in theory simply work (by setting "Python binary path" to `/path-to-folder/myproject-virtualenv37/bin/python3.7`). However, when trying to start the server I get:

```
import frida
ImportError: No module named frida
```

in bridaServicePyro.py. This doesn't make any sense. When I edit bridaServicePyro.py to do a `print(sys.executable)` before the frida import fails, Brida prints that the correct virtualenv python binary is used (`/path-to-folder/myproject-virtualenv37/bin/python3.7`). Even when I do `print(sys.path)` I do get the correct paths, including `/path-to-folder/myproject-virtualenv37/lib/python3.7/site-packages` where frida is really installed (I checked).

On a shell it works fine and frida is actually installed:

```
$ ./myproject-virtualenv37/bin/python3.7
Python 3.7.5 [...]
>>> import frida
>>> exit()
```

I've read a little bit about this problem on https://stackoverflow.com/questions/37211115/how-to-enable-a-virtualenv-in-a-systemd-service-unit and as far as I understand, the usage of the correct python binary should actually work, but doesn't. Any thoughts on this? Is this Jython messing with me? Did you get virtualenvs running yourselves?

**Comment by federicodotta** [comment]
Hi @floyd-fuh 

I'm working on a solution to handle python virutal env. I will back on you as soon as it will be ready.

Have a nice day,
Federico

**Comment by federicodotta** [comment]
Hi @floyd-fuh,

virtual environment support has been added with commit f59c7626e44b9e4c4e9799d1e2a6a0108b5ebb45

I write two ways to handle virtual envs. The one currently enabled adds two environment variables to the Java Runtime.exec and at the moment seems to be the better solution. The second one (commented in the code) executes the command that activates the virtual env and then runs the python server in that context.

Please let me know if it solve your issue.

Federico

**Comment by floyd-fuh** [comment]
This is very cool, thank you. But I wanted to let you know that I'm super busy at the moment, but the next time I have project where Brida fits I'll definitely check it out! Unfortunately I don't have time to check it out just now, sorry about that.
