### ISSUE TITLE
Unable to find executable

### ISSUE THREAD

**Issue by mustafairan** [federicodotta/Brida#57]
When I click spawn, I get the following error. I m sure that package name is correct (com.myapplication.stage). What could be the problem?

Exception with spawn application net.razorvine.pyro.PyroException: [frida.ExecutableNotFoundError] unable to find executable at 'com.myapplication.stage' net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2713) java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) java.base/java.lang.Thread.run(Thread.java:830)

**Comment by federicodotta** [comment]
Hi @mustafairan 

Please paste a screenshot of Brida configuration pane.

Have you check the right option between Remote/USB/Local? Local is for local processes (like Windows/OS X ones), USB is fro USB connected devices and Remote if you are using port redirection.

Federico

**Comment by nyxman-dev** [comment]
The same issue
Burp 2020.4 + GenyMotion v 3.1.0
![BRIDA_Exception](https://user-images.githubusercontent.com/60509908/83746690-240f1800-a668-11ea-939c-95b64de6c8ea.png)

**Comment by federicodotta** [comment]
As wrote in the other issue, you have to choose "Frida USB" instead of "Frida local"

**Comment by mustafairan** [comment]
As @federicodotta says, I have solved my problem. Thanks.
