### ISSUE TITLE
unable to find method 'getplatform'

### ISSUE THREAD

**Issue by oynomed** [federicodotta/Brida#58]
Application spawned correctly but i get error  unable to find method 'getplatform'
see screenshots:
https://i.imgur.com/WDQuOYd.png

FYI:
i'm using Genymotion as emulator
and also using the script, see screenshots https://i.imgur.com/W2wkh9O.png as Frida JS files folder.

**Comment by federicodotta** [comment]
Hi, this script is old. If you are using last version of Brida you have to click on "Load default JS files" and choose a folder in which Frida default files will be copied. See the Wiki for detailed instructions.

**Comment by oynomed** [comment]
thanks, problem solved
