### ISSUE TITLE
env: node: No Such File or Directory

### ISSUE THREAD

**Issue by Teeroy-tk** [federicodotta/Brida#59]
I've installed everything, and can access the phone via frida and burp. The server is up and running fine. I find the application ID via frida (either by PID or by name) and enter it. Upon "Attach Application" I get the error "env: node: No such file or directory" which would appear to indicate a problem with node, but I don't see anything wrong with the node install or the frida-compile install.

I have even uninstalled and then reinstalled all of node/frida components.

Attached is an image of my configuration screen.

Host is Mac osx Catalina 10.15.3, iphone 7 (pre A12 frida profile) via USB.

![Screen Shot 2020-06-10 at 12 29 38 PM](https://user-images.githubusercontent.com/66743137/84295418-8eb4cd80-ab18-11ea-9ba8-68c9f875d947.png)

**Comment by Teeroy-tk** [comment]
Found answer in another thread.

**Comment by klmitchell2** [comment]
@Teeroy-tk , what thread?
