### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by yannayl** [federicodotta/Brida#6]
Hello,
Can you please provide build instructions? I failed to build it on my Ubuntu machine (but I have never used Maven before, so I am probably missing something).
Thanks

**Comment by federicodotta** [comment]
Hi! I will add some basical build instruction but it is a standard Maven project. You can for example import the project as Maven project in Eclipse and then execute the Maven project with goal "package".

If you need only Brida binary (and you don't want to modify Brida code) you can download compiled Brida package from "Release" tab of GitHub.

Federico
