### ISSUE TITLE
App crash when using Graphical Analysis tab

### ISSUE THREAD

**Issue by andyacer** [federicodotta/Brida#60]
Hi, 

I'm getting unexplained app crashes when using the Graphical Analysis tab.  I believe this happens with other functionality as well, though I haven't pin pointed those situation.  The application I'm instrumenting seems to crash within minutes of being spawned by Brida.  The only error output I get is from Android's logcat output for the app, which is the following:

> libc++abi  E  terminating with uncaught exception of type std::runtime_error:
> libc            F  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27238 (GDServiceHelper), pid 27186 (lthscreeningsit)
> DEBUG      F  #00 pc 0000000000071d34  /system/lib64/libc.so (offset 0x71000) (tgkill+8)
>                    F  #\01 pc 0000000002ebd8b8  /data/app/com.android.chrome-ga_x5fDQFUvRP5L29ioAaQ==/base.apk (offset 0xbec000)`

Is there a Discord or Keybase group for Brida users where people can discuss individual problems like this?  My issue is probably too app-specific to be a real issue with the overall Brida plugin.

This is on Android 9, frida 12.9.7, Brida 0.4.   Also, thanks for making Brida.  I'm so glad that this tool exists.

**Comment by federicodotta** [comment]
Hi @andyacer,

unfortunately there is not a group related to Brida but probably there are many related to Frida itself. 

Have you tried to spawn the application directly with Frida with some hooks in order to understand if your issue is related to some JS code used by Brida or generally with Frida?

**Comment by andyacer** [comment]
Hi Federico! I haven't yet, that's a good idea.  I'll give that a shot and report back.  Thanks

**Comment by andyacer** [comment]
Ok, the app crashes the same way while only using Frida itself and a single hook, no Brida involved.  I'm wondering if it's doing some kind of integrity check once every few minutes and self-terminating if it fails.  The mystery continues.

I'll close this issue, thanks for the reply =)
