### ISSUE TITLE
Inspect method not working

### ISSUE THREAD

**Issue by ddiptg** [federicodotta/Brida#64]
inspect method "add" and click the text, logcat print the log, but brida not print anything

<img width="752" alt="code" src="https://user-images.githubusercontent.com/17867028/96092825-f8e1e280-0efd-11eb-8ead-716f77598b05.png">
<img width="948" alt="brida" src="https://user-images.githubusercontent.com/17867028/96092828-f97a7900-0efd-11eb-8e57-c6cf7888dab4.png">

**Comment by aoushakov** [comment]
how did you solve it?
