### ISSUE TITLE
Brida0.4:Exception with spawn application

### ISSUE THREAD

**Issue by ramoncjs3** [federicodotta/Brida#65]
ENV:
burp2020
brida0.4
macos 10.15.6

STACK:

Exception with spawn application java.util.concurrent.ExecutionException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap') java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) burp.BurpExtender.executePyroCall(BurpExtender.java:2726) burp.BurpExtender.spawnApplication(BurpExtender.java:2762) burp.BurpExtender.actionPerformed(BurpExtender.java:2900) java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) java.desktop/java.awt.Component.processMouseEvent(Component.java:6636) java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) java.desktop/java.awt.Component.processEvent(Component.java:6401) java.desktop/java.awt.Container.processEvent(Container.java:2263) java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) java.desktop/java.awt.Component.dispatchEvent(Component.java:4844) java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919) java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548) java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764) java.desktop/java.awt.Component.dispatchEvent(Component.java:4844) java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)  

I really use scriptBridaDefault.js , it dose not works.

![image](https://user-images.githubusercontent.com/33519654/96820074-b6695a00-1457-11eb-9e64-6d17ede43ea0.png)

**Comment by federicodotta** [comment]
Frida JS files folder should contain the folder of the Brida files and not the path of a single file. You have to use the "Load default JS files" button to load Brida HS files and then, if you want, add your own hooks to "brida.js" file. But the "Frida JS files folder" should be the path of the folder and not of a single file. See the documentation for more details.

Federico

**Comment by ramoncjs3** [comment]
> Frida JS文件文件夹应该包含Brida文件的文件夹，而不是单个文件的路径。您必须使用“加载默认JS文件”按钮来加载Brida HS文件，然后根据需要将自己的钩子添加到“ brida.js”文件中。但是“ Frida JS文件文件夹”应该是文件夹的路径，而不是单个文件的路径。有关更多详细信息，请参见文档。
> 
> 费德里科

![image](https://user-images.githubusercontent.com/33519654/97133251-4e32b500-1784-11eb-8226-8cc3f76e42ef.png)

But......still can't work...........

**Comment by young-peng** [comment]
> > Frida JS文件文件夹应该包含Brida文件的文件夹，而不是单个文件的路径。您必须使用“加载默认JS文件”按钮来加载Brida HS文件，然后根据需要将自己的钩子添加到“ brida.js”文件中。但是“ Frida JS文件文件夹”应该是文件夹的路径，而不是单个文件的路径。有关更多详细信息，请参见文档。
> > 费德里科
> 
> ![image](https://user-images.githubusercontent.com/33519654/97133251-4e32b500-1784-11eb-8226-8cc3f76e42ef.png)
> 
> But......still can't work...........

npm i frida-compile@9.4.0

**Comment by federicodotta** [comment]
Hi @ramoncjs3 @young-peng 

Please try again with Brida 0.5 and with the JS file pushed with commit 21ec48ff43bcdc621e40f3782b1298a76310fb58, that can be used with frida-compile >= 10. 

It is not necessary to manually compile Brida. You can use the last release (Brida 0.5), using the following JS files from the Git repository instead of the ones packed with the release:

* res/androidDefaultHooks.js
* res/brida.js
* res/bridaFunctions.js
* res/iosDefaultHooks.js

Federico

**Comment by bigrob69** [comment]
Should I log a new issue ?
