### ISSUE TITLE
Error during frida-compile. Aborting

### ISSUE THREAD

**Issue by TraeMazza** [federicodotta/Brida#67]
the current release of frida-compile (version: 10.0.0) does not contain the '-x' option, which seems to break attaching/spawning an app.

![frida_help](https://user-images.githubusercontent.com/21281325/97317263-fe65f380-1840-11eb-8f1a-6e0db6a6e660.png)

In the Brida configurations tab, I get the error in the screenshot below when I attempt to perform any spawn or attach actions.

<img width="1438" alt="brida_config" src="https://user-images.githubusercontent.com/21281325/97317633-61578a80-1841-11eb-88db-ab6b31464f49.png">

Is there an older version of frida-compile users can pull that is known to work? or another workaround?

Appreciate the help and the project :)

**Comment by d3vilbug** [comment]
same here 
![image](https://user-images.githubusercontent.com/13887305/97419911-78bf7200-192c-11eb-81d7-c56330568610.png)

**Comment by d3vilbug** [comment]
meanwhile @TraeMazza  you can switch to the older version of frida-compile and It is working fine on 

> npm i frida-compile@9.4.0 

not working with latest i guess

**Comment by rank0** [comment]
I have your same issue on MacOS，How did you solve it in the end？

**Comment by d3vilbug** [comment]
> I have your same issue on MacOS，How did you solve it in the end？

https://github.com/federicodotta/Brida/issues/67#issuecomment-717823379

**Comment by federicodotta** [comment]
Hi, in the last version of frida-compile the "-x" option that i I use in Brida has been removed. I will in these days publish a release without the "-x" option. Meanwhile you can downgrade frida-compile to version 9.

Federico

**Comment by 24h7d** [comment]
> Hi, in the last version of frida-compile the "-x" option that i I use in Brida has been removed. I will in these days publish a release without the "-x" option. Meanwhile you can downgrade frida-compile to version 9.
> 
> Federico

I still facing this problem. are the update of frida-compile is already released? I install the frida-compile with npm command.
thanks

**Comment by federicodotta** [comment]
Hi @d3vilbug , @TraeMazza , @rank0 and @24h7d ,

I just fixed the issue in commit d5915fc701667e687c761a3ed605ad575abfc835.

Now Brida works with frida-compile 10 by default and by checking the new "Use old version of frida-compile" checkbox in the "Configurations" tab it is also possible to use Brida with frida-compile 9 and lower.

Please let me know if your issues are fixed.

Federico

**Comment by federicodotta** [comment]
No, unfortunately there is a compilation bug with frida-compile 10 that I'm trying to solve. At the moment the best option is to continue to use version 9.X.

Federico

**Comment by federicodotta** [comment]
Hi @d3vilbug @TraeMazza @rank0 @24h7d,

The JS file pushed with commit 21ec48ff43bcdc621e40f3782b1298a76310fb58 can be used with frida-compile >= 10. 

It is not necessary to manually compile Brida. You can use the last release (Brida 0.5), using the following JS files from the Git repository instead of the ones packed with the release:

* res/androidDefaultHooks.js
* res/brida.js
* res/bridaFunctions.js
* res/iosDefaultHooks.js

Please let me know if you have any issue.

Federico
