### ISSUE TITLE
[Rooting Check Bypass] not working.

### ISSUE THREAD

**Issue by 24h7d** [federicodotta/Brida#70]
I think the hook and function for Rooting Check Bypass is **not working**. 
with the same script that i found in androidDefaultHook.js and trying to use it in frida -U -l **script.js** -f package_name --no-pause its working perfectly to bypassing root checking mechanism.

When the Rooting Check Bypass enabled, there nothing log showing up in console. (as if I enabled the SSL Pinning bypass there are a lot of log).

I use **Brida 0.4** and **frida-compile 9.5.2**

thanks for all attention.

**Comment by federicodotta** [comment]
Hi @24h7d, 

the bug now should be fixed (commit c72aa30e4ee6aa55244a81413278b5c9ff395c10).

Please let me know if it works correctly.

I compiled a new pre-prelease up to the last commit. You can find the release here:
https://github.com/federicodotta/Brida/releases/tag/v0.5pre

Thank you,
Federico

**Comment by federicodotta** [comment]
Hi @24h7d,

I close the issue because it should be solved. Please open a new one if you have still issues.

Federico
