### ISSUE TITLE
Error in Graphical Analysis

### ISSUE THREAD

**Issue by oynomed** [federicodotta/Brida#73]
When I click in Module and double click the library, I encounter this error, see screenshots
https://i.imgur.com/tFmPd62.png

**Comment by federicodotta** [comment]
Hi @oynomed,

"script is destroyed" error usually means that the application and/or the frida-server are crashed or simply the application has been closed/detached.

The "Graphical analysis" view is dynamically populated using Frida. When you double-click on a module, the list of methods is retrieved using Frida and if the application is crashed or detached you get an error.

Try lo respawn/reattach the application and repeat the operation (it is not necessary to click again on the "Load tree" button if you don't change the application you are testing).

Federico

**Comment by oynomed** [comment]
Hmmm, only that specific application gives the error, I test on other app and has no problem.
you can close this issues now.
