### ISSUE TITLE
Compile & Spawn problem

### ISSUE THREAD

**Issue by akifalioglu** [federicodotta/Brida#77]
(node:7592) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\***\node_modules\mold-source-map\package.json' of 'mold-source-map.js'. Please either fix that or report it to the module author. I get an error saying. 
(Use `node --trace-deprecation ...` to show where the warning was created).
!

My frida-compile version is 9. Thanks..

(https://user-images.githubusercontent.com/37072981/117557132-93f80080-b078-11eb-992a-0b85b38396f6.png)

**Comment by federicodotta** [comment]
Hi @akifalioglu 

uhmm... It seems to be an issue caused one of frida-compile dependencies (mold-souce-map). Probably the last version of NodeJS is not compatible with package.json file of that dependency.

I will make some tests. Meanwhile you can try to use an older version of NodeJS.

Federico

**Comment by akifalioglu** [comment]
Thanks.. https://nodejs.org/dist/v13.12.0/ im downloaded older version and problem solved..
