### ISSUE TITLE
frida-remote

### ISSUE THREAD

**Issue by FreaxW** [federicodotta/Brida#80]
How to configure host and port in brida when using remote connection frida server.

**Comment by federicodotta** [comment]
Hi @FreaxW, the "Remote" option of Brida is the "-R" option of Frida, that uses the default port 27042/TCP.

If you need to set the Frida server to listen on a different port with Android, you can use "adb forward" to forward the port to the port 27042 of your client and then use the "Remote" option of Brida.

Federico

**Comment by federicodotta** [comment]
Hi @FreaxW,

I close the issue. Please open another one if you need more help.

Federico
