### ISSUE TITLE
Pyro Frida parse error

### ISSUE THREAD

**Issue by ChrisMcMStone** [federicodotta/Brida#82]
Hi, 

I'm trying to test an app on the Genymotion emulation with Brida. I'm being forced to use an older version of Frida (12.9.7) since I can't get more recent versions to work with the emulator. I've tried both versions 9 & 10 of frida-compile.

I have configured Brida as per the Wiki instructions, with the configuration in the image below. 

![IMAGE 2021-07-22 14:17:49](https://user-images.githubusercontent.com/6391789/126645299-ff4a84b6-bd4f-4314-a1c6-c402d9f74786.jpg)

As you can see, the Pyro server launches fine, however an error occurs with the message below whenever I try to spawn an application via Brida. Note that the application does indeed launch and doesn't crash. 

![IMAGE 2021-07-22 14:51:46](https://user-images.githubusercontent.com/6391789/126650399-8d523107-b53d-4017-8203-000164f5947b.jpg)

Any help debugging this would be much appreciated!

**Comment by federicodotta** [comment]
Hi @ChrisMcMStone,

it seems to be a parse error in JS files used by Brida.  

Can you try to run Brida using default Brida files without modifications (you can use the "Load default JS files" button to load a copy of the default Brida files somewhere in your filesystem) using Frida-compile 9 (there is a bug in frida-compile 10 not already solved) both checking and unchecking the flag "Use old version of frida-compile"?

Frida-compile compiles the Brida JS files in a file named "bridaGeneratedCompiledOutput.js" that you can find in the same directory of other Brida files. You can check at line 2396 of that file to see if there is something wrong.

Please let me know the result of these tests.

Federico

**Comment by ChrisMcMStone** [comment]
Hi @federicodotta,

Thank you for your response. Your suggestion did indeed resolve my issue, I was obviously loading the default Brida JS files with the wrong path. 

Thanks
