### ISSUE TITLE
argument not right

### ISSUE THREAD

**Issue by Drea1v1** [federicodotta/Brida#84]
When I executed the method - base64encode, I got below on the console. The output was not correct,argument one is null ,argument three is equal arg2,what wrong?

argument list : 1111
                         2222
                         3333

my base64encode function :
```js
base64encode: function(arg1,arg2,arg3) {
console.log("enter base64encode")
console.log('1:'+arg1,'2:'+arg2,'3:'+arg3)
........SOMETHING hook .........
}
```
my output:
`
enter base64encode
1: 2:1111 3:2222
`

Additional info:
- Brida version: 0.4
- Frida version: 14.2.18
- OS:Mac OS 10.15
- Burp version: v2.1
- Java version:1.8.0_144

**Comment by federicodotta** [comment]
Hi @Drea1v1

one question. Are you calling that method from the "Debug export" section or from a custom plugin? In this latter case, can you send me the plugin configuration (if you created the plugin from the GUI) or the snippet of code that calls the base64encode method (if you are writing a custom plugin in Java/Python)?

Thank you!
Federico

**Comment by federicodotta** [comment]
Hi @Drea1v1,

I close the issue. If you need more help please open another one.

Federico
