### ISSUE TITLE
binary data received from frida error - HELP!

### ISSUE THREAD

**Issue by renzyang** [federicodotta/Brida#89]
hey!

I was trying to make IMessageEditorTab plugin work, here is how I set the plugin configuration and what I did in my script:
1. brida setting
the entire http body is encrypted data( binary form), so I choose [ASCII-HEX] to encode or decode data sent to or received from frida exported function;
![image](https://user-images.githubusercontent.com/34933348/134470584-05e95642-fd2c-40b6-8ebc-cbcbcf4aa30e.png)

2. frida exported function
- decryptresponse
```js
  decryptresponse: function (req) {
	if (ObjC.available) {
		var dic = {0:0, 1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7, 8:8, 9:9, a:10, b:11, c:12, d:13, e:14, f:15};

		var reqLen = req.length/2;
		var add1 = [];
		for(var i=0; i<reqLen; i++){
			var num = dic[req[i*2]]*16+dic[req[i*2+1]];
			add1.push(num);
		}
		const addr = Memory.alloc(reqLen);
		Memory.writeByteArray(addr,add1);
		var data = ObjC.classes.NSData.dataWithBytes_length_(ptr(addr), reqLen);

		var myObj=ObjC.chooseSync(ObjC.classes.MyObj)[0];
		var decryptedData = myObj["- decryptData:"](data);
		var decryptedString = ObjC.classes.NSString.alloc()["- initWithData:encoding:"](decryptedData, 4);

		return decryptedString .toString();
	}
  }
```
- encryptrequest
```js
  encryptrequest: function (req) {
	 if (ObjC.available) {
		 var backToNsstring = ObjC.classes.NSString.stringWithUTF8String_(Memory.allocUtf8String(req)); 
		 var backToData = backToNsstring["- dataUsingEncoding:"](4);         
		 var errorPtr2 = Memory.alloc(Process.pointerSize);
		 Memory.writePointer(errorPtr2, NULL); 
		 var backToDict = ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_(backToData, 1, errorPtr2);
		 
		 var myObj=ObjC.chooseSync(ObjC.classes.MyObj)[0];
                 var decryptData = myObj["- encryptDict:"](backToDict);
		 
		 var data_len = decryptData.toString().length;
		 var circle_i = 0;
		 var decryptDataToHex = "";
		 for(var i=1; i<data_len; i++){
			 if(circle_i<8){
				 decryptDataToHex = decryptDataToHex + decryptData.toString()[i]
				 circle_i++;
			 }else{
				 circle_i = circle_i % 8;
			 }
		 }
		return decryptDataToHex ;
	 }
  }
```

Decrypting(using function **decryptresponse**) original http data works fine, and re-encrypting(using function **encryptrequest**) edited data( same message) seems work too! Because I print received data(which is **req**) in decryptresponse and to-be-returned data(which is **decryptDataToHex**) in encryptrequest, and it turns out that they are the same!

Something happens when decryptDataToHex is sent to burp! Some data somehow was changed to `3f` and one byte was lost during transmission. here is the log I print to prove my idea. The second [--===method: decryptresponse===---] part shows the binary data received from burp(same as hex data shown in burp Hex Tab), which is exactly the **decryptDataToHex** returned from frida but somehow not same( most parts match except some bytes being changed to `3f`);

![image](https://user-images.githubusercontent.com/34933348/134476301-975b8b3b-49de-4f18-9e3a-f5563c040a9a.png)

I think the general logic is correct but I don't know what is the matter... 😭 

help plz!!!!

**Comment by federicodotta** [comment]
Hi @renzyang,

uhmm... very strange situation.

I see that you implemented ASCII-HEX encoding/decoding... In order to be sure that the issue is not caused by something strange that happens there, you can try to use Base64 instead of Ascii-Hex.

IOS has some built-in method to encode/decode NSData to Base64, and Base64 encoding is supported also in Brida.

Please try the following approach:

1. In "Encode function paramaters" change ASCII-HEX in Base64
2. In "decryptresponse" function create an NSData from the Base64 string supplied by Brida using the following function: `var obj3 = ObjC.classes.NSData.alloc().initWithBase64EncodedString_options_("BASE_64_ENCODED_STRING",0);` 
3. If the value returned by the "decryptresponse" function after the decryption is still binary, it is better to add an encoding also to the return value, in order to avoid passing binary data back and forth (that often create misalignments). You can encode the return value using the Base64 encoding method of NSData described in the following point to encode the return value of the "decryptresponse" function and then decoding it in your plugin using the "Decode function output" option of Brida
4. In the "encryptrequest" function you can encode the NSData returned by your encryption function '- encryptDict' (it is an NSData, is it right?) using the "base64EncodedStringWithOptions" function of NSData as follows: `decryptData.base64EncodedStringWithOptions_(0)` (it returns an NSString encoded in Base64). Then you can Base64 decode this string in your plugin by changing the "Decode output of Frida function on edited content" from ASCII-HEX to Base64

I hope I was clear. I'm not sure that my approach works with your specific situation because I don't know the details, but I think it can solve your problem.

One last thing: in the brida.js files you can find some useful JS functions for bytes/hex/base64 transformations.

Please let me know if the following approach works.

Federico

**Comment by renzyang** [comment]
Hi, @federicodotta 

Thanks for your help! I followed your advice, but I am afraid that it didn't work and I got a similar error... 😢 Here is the detail: 

1. brida setting
![image](https://user-images.githubusercontent.com/34933348/134512119-b08bbb9a-d29c-40f0-a008-51f559f3b7ff.png)

2. frida exported function
```js
  decryptresponse: function (req) {
	if (ObjC.available) {		
		var data = ObjC.classes.NSData.alloc().initWithBase64EncodedString_options_(req,0);
		var myObj=ObjC.chooseSync(ObjC.classes.MyObj)[0];
		var decryptedData = myObj["- decryptData:"](data);
		
		var decryptedDataBase64 = decryptedData.base64EncodedStringWithOptions_(0);
		return decryptedDataBase64.toString();
	}
  },

  encryptrequest: function (req) {
	 if (ObjC.available) {
		 var backToData = ObjC.classes.NSData.alloc().initWithBase64EncodedString_options_(req,0);
		 var errorPtr2 = Memory.alloc(Process.pointerSize);
		 Memory.writePointer(errorPtr2, NULL); 
		 var backToDict = ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_(backToData, 1, errorPtr2); 
		 
		 var myObj=ObjC.chooseSync(ObjC.classes.MyObj)[0];
                 var encryptData = myObj["- encryptDict:"](backToDict);

		 var encryptDataBase64 = encryptData.base64EncodedStringWithOptions_(0);
		 return encryptDataBase64.toString();
	 }
  }

```
I also print some specific variables(which are **data** in decryptresponse function and **encryptData** in encryptrequest function ) as did in 'ASCII-HEX version' to verify that data is correctly decrypted/encrypted.

problem is the same: 1. Some data somehow was changed to `3f`   2. one byte was lost during transmission (returned from encryptrequest function).

![image](https://user-images.githubusercontent.com/34933348/134515631-ebfaa3b2-e93f-4843-9b83-baa027600c5a.png)

more info may help find out the problem:
1. firstly, click brida sub-tab to decrypt request body. (work)
2. edit the tab (no change actually) to invoke re-encryption function (which is encryptrequest in this situation). (seems work)
3. re-click brida sub-tab to decrypt re-encrypyted message. (fail. because data is not the same as mentioned)

- version:
    - brida: 0.5_pre2
    - IOS: 12.5.4 rooted(unC0ver)
    - windows10
    - burpSuite: professional v2.1.04

**Comment by federicodotta** [comment]
Hi @renzyang,

1) Before digging in further, can you please make this check in order to be sure that decryptData e encryptDict don't work differently? Can you please change the decryptresponse function as follow and check if "data" and "encryptData" are equals this way?

```JavaScript
  decryptresponse: function (req) {
	if (ObjC.available) {		
		var data = ObjC.classes.NSData.alloc().initWithBase64EncodedString_options_(req,0);
                // PRINT DATA
		var myObj=ObjC.chooseSync(ObjC.classes.MyObj)[0];
		var decryptedData = myObj["- decryptData:"](data);
                // PRINT DECRYPTED DATA		
		 var errorPtr2 = Memory.alloc(Process.pointerSize);
		 Memory.writePointer(errorPtr2, NULL); 
		 var backToDict = ObjC.classes.NSJSONSerialization.JSONObjectWithData_options_error_(decryptedData, 1, errorPtr2); 
                var encryptData = myObj["- encryptDict:"](backToDict);
                // PRINT encryptData.
		var decryptedDataBase64 = decryptedData.base64EncodedStringWithOptions_(0);
		return decryptedDataBase64.toString();
	}
  },
```

2) Have you tried to send the encrypted object to the backend to see if it is accepted? Maybe something during the JSON serialization can change but maybe the output is well formatted.

3) When you edit the value in the tab (also without changing anything), the data in the edited tab that you edit are binary? If yes, maybe something wrong happens there. You can make a try to remove the Base64 value from the settings "Decode function output" and "Encode input passed to Frida function executed on edited contente" of Brida. In this way you will find a Base64 encoded value in the Edited Tab. You can manually decode it, change something and encode it again, to check if in this way it works correctly.

Please let me know if something work.

Federico

**Comment by renzyang** [comment]
Hi @federicodotta,

Thanks for your advice! here is verification:

1. I re-wrote the decryptresponse function as you told, and the **data** and **encryptData** are the same! 
2. The backend does respond to the encrypted request/body (No edit. Response body is also encrypted)
3. The data I edit is in json format actually and I just edit it without changing anything like this:
![image](https://user-images.githubusercontent.com/34933348/134622103-40b09c18-a1e2-4066-b382-a4ebcf406633.png)

Followed your advice(the 3rd point) and I found something new. This time, I removed the [Base64] from only `Decode output of Frida function executed on edited content` (others stay the same) to see whether data changes during transmission (returned from encryptrequest function) or not. And the answer is NO! 

Here is the detail I print: 

![c3ba9db2f54ac35c59a67e5fa52b0b4](https://user-images.githubusercontent.com/34933348/134626168-e0b2e73b-a607-40c6-b239-fdc685df0820.png)

You mentioned that something may happen when I edited, but encryptrequest function receives right data and will return the same base64 data as decryptreponse function received( shown in the above image). So editing may have nothing to do with this problem, right?

When I only removed the [Base64] from `Decode output of Frida function executed on edited content `, Burp received correct base64 data as frida( encryptrequest function) returned. When re-added [Base64], decoding went wrong (**I am not sure**). And here is the comparison between original hex data and re-encrypted hex data:

![a9258a504ee9826760eebc8aa6f9aad](https://user-images.githubusercontent.com/34933348/134628923-f0795761-53ac-4088-b946-e952d640bd8c.png)

Is there any problem in Base64 decoding algorithm in brida? I will verify the base64 data decoding to binary data and encoding back, though I don't know how to do it for now.

besides, 
the binary data in burp hex tab is (which is the same as data/decryptedData in decryptresponse/encryptrequest function): 
```
000001f5 1c2f6572 64c2b76f f12e3e09 3be2b60d a42b7ac1 dac21de8 2c533d1c 8780a521 b3604d03 ecd077b1 19f95396 f881c6a5 3a7cef8e 73060d49 91965000 912158ee fcf17b74 c353c8dd 4dbe5a5e d6c6c046 a992db39 dff38a1b 88daa16d 47ee8255 3b540e98 63394fb8 89f65664 08ae0d1c 0b5e962f 52ac8f72 f0b5c748 6c76f79a 685315ea 5a3128b7 4569aaf8 ad49052b aeb898e2 5f5fcb92 50317e88 0c7db547 6fb38a93 edb76c48 418a70c6 ebee9407 9cee68f5 3278dfba 027e9217 a46a7b86 339d9fa1 cdef00ad c42f2c63 6b6fad9e a9d75202 c6adaef1 7cde7e89 3adedfd2 a9b65692 c669a159 884bcb77 1f64a180 ee618ee2 44d39465 d097cde7 ceb34c03 fcc5fa28 a0aa9c1f ca5565f0 e6c4bb8a 3c4a8bdb f1a02de7 c3c6fe31 af951857 aad3951f f15b926a 23c10d66 d8ee4549 8261c3f1 eaa5e0b1 527b1b62 5b7995c6
```
and its base64 encoded data from brida is:
```
AAAB9RwvZXJkwrdv8S4+CTvitg2kK3rB2sId6CxTPRyHgKUhs2BNA+zQd7EZ+VOW+IHGpTp8745zBg1JkZZQAJEhWO788Xt0w1PI3U2+Wl7WxsBGqZLbOd/zihuI2qFtR+6CVTtUDphjOU+4ifZWZAiuDRwLXpYvUqyPcvC1x0hsdveaaFMV6loxKLdFaar4rUkFK664mOJfX8uSUDF+iAx9tUdvs4qT7bdsSEGKcMbr7pQHnO5o9TJ437oCfpIXpGp7hjOdn6HN7wCtxC8sY2tvrZ6p11ICxq2u8Xzefok63t/SqbZWksZpoVmIS8t3H2ShgO5hjuJE05Rl0JfN586zTAP8xfoooKqcH8pVZfDmxLuKPEqL2/GgLefDxv4xr5UYV6rTlR/xW5JqI8ENZtjuRUmCYcPx6qXgsVJ7G2JbeZXG
```

Thanks again for your time! 😭

**Comment by renzyang** [comment]
Hi, @federicodotta,

It turns out that my direction is correct! It's not because of the base64 decode algorithm, but the process of passing data to Burp!

I studied the code of `BridaMessageEditorPlugin.java` and `CustomPlugin.java` and found the data processing path( customPluginEditedContentLocation == BridaMessageEditorPluginOutputLocation.BODY):

1. --=(returned from frida)=-->  **String ret**  
2. --=(base64 decoded in decodeCustomPluginOutput)=-->  **byte[] customPluginEditedContentOutputDecoded** 
3. --=(re-encoded in encodeCustomPluginValue)=--> **String customPluginEditedContentOutputEncoded**  
4. --=(bodyString.getBytes() in replaceOutputBody)=--> **byte[] newHttpMessage** 

So in my situation, after decode from base64 data, customPluginEditedContentOutputDecoded is already the binary data I need! But the following code just changes the data and leads to my situation. Test code is as followed:
```java 
@Test
    public void testForDecode(){
        String base64String = "AAAB9RwvZXJkwrdv8S4+CTvitg2kK3rB2sId6CxTPRyHgKUhs2BNA+zQd7EZ+VOW+IHGpTp8745zBg1JkZZQAJEhWO788Xt0w1PI3U2+Wl7WxsBGqZLbOd/zihuI2qFtR+6CVTtUDphjOU+4ifZWZAiuDRwLXpYvUqyPcvC1x0hsdveaaFMV6loxKLdFaar4rUkFK664mOJfX8uSUDF+iAx9tUdvs4qT7bdsSEGKcMbr7pQHnO5o9TJ437oCfpIXpGp7hjOdn6HN7wCtxC8sY2tvrZ6p11ICxq2u8Xzefok63t/SqbZWksZpoVmIS8t3H2ShgO5hjuJE05Rl0JfN586zTAP8xfoooKqcH8pVZfDmxLuKPEqL2/GgLefDxv4xr5UYV6rTlR/xW5JqI8ENZtjuRUmCYcPx6qXgsVJ7G2JbeZXG";
        byte[]  base64StringBytes = base64String.getBytes();
        byte[] outputBytes = Base64.decodeBase64(base64StringBytes);
        String outputBytesString = new String(outputBytes);
        byte[] outputBytesStringBytes = outputBytesString.getBytes();
        return;
    }
```
![image](https://user-images.githubusercontent.com/34933348/135014398-d077f1a5-e7c9-46ba-9fb4-069c265d0354.png)

When I change the code and just use customPluginEditedContentOutputDecoded in replaceOutputBody function, things work in my situation( I could encrypt the edited data and re-decryption works fine!)

So I think there may be some improvement to be done in Brida.

**Comment by federicodotta** [comment]
Hi @renzyang,

sorry but in the last days I was very busy and I could not help with your issue.

Thank you a lot for your great analysis. It is very helpful for me! 

I will try to fix this issue as soon as possible, trying to remove all the place in which the value is converted from bytes to String. Unfortunately, the return value from Frida must be a string (for this reason it is better to apply an encoding) but if I converted to String also inside Burp I will try to fix it, leaving always data in byte array form.

I will let you know as soon as possible.

Thanks again!
Federico

**Comment by federicodotta** [comment]
Hi @renzyang,

I made a quick modifications to the code in order to threat arguments as byte[] without converting them to Strings.

I coded this build without even try it because at the moment I could not run frida, so it could be broken.

I kept the argument as byte[] as much as I could but I have to convert them to Strings before passing them to Frida as arguments.

Please let me know if this build fix your issue. If so, I will execute more testing on my code and commit it to the public repo.

(You have to unzip my attachment. The jar is inside a zip because GitHub does not allow to upload directly jars...)

Federico
[Brida-0.5-jar-with-dependencies.zip](https://github.com/federicodotta/Brida/files/7244280/Brida-0.5-jar-with-dependencies.zip)

**Comment by renzyang** [comment]
Hi, @federicodotta,

Sorry for the late reply. I found that it did not work.

Here I tested both the plugin I rebuilt and yours with the same configuration, but yours exported some error in brida console:

![584df0e216a209bea98d00e0f3fa640](https://user-images.githubusercontent.com/34933348/135376091-7596ac80-f701-4405-843d-5363765a6a70.png)
![f0f50a33e2a25d34ae2d42d374b8e59](https://user-images.githubusercontent.com/34933348/135376104-69a51366-c192-4773-badf-5585b55af122.png)

By the way, **customPluginEditedContentOutputDecoded**(byte[]) could not be converted to String type if `Encode output` is not configured, and that's just my two cents. Haha...

renz

**Comment by federicodotta** [comment]
Hi @renzyang,

sorry, changing the type of the argument requires a lot of modifications all over the plugin and I made these changes very fast without even trying them... I will try my modifications and fix the issues as soon as possible...

Furthermore, in addition to try to maintain arguments in byte[] as much as I can, I will try to use ISO-8859-1 encoding when I pass from byte[] to String and from String to byte[], as described in [this StackOverflow post](https://stackoverflow.com/questions/9098022/problems-converting-byte-array-to-string-and-back-to-byte-array):

This encoding should not change the bytes during the conversion. Can you please try the following code with your specific byte array?

```Java
String decoded = new String(encryptedByteArray, "ISO-8859-1");
System.out.println("decoded:" + decoded);

byte[] encoded = decoded.getBytes("ISO-8859-1"); 
System.out.println("encoded:" + java.util.Arrays.toString(encoded));
```

**Comment by renzyang** [comment]
Hey, @federicodotta,

I made a quick test and this little change may really solve this problem! See here:
![image](https://user-images.githubusercontent.com/34933348/135435137-2c3e280e-8b09-4117-b0f6-ae404a7d9237.png)

**Comment by federicodotta** [comment]
Hi @renzyang 

perfect! I will fix the byte[] issues and apply this encoding to all the strings.

I will let you know as soon as the build will be ready.

Thank you for your help,
Federico

**Comment by federicodotta** [comment]
Hi @renzyang,

sorry for the long time passed but I have personal issues and I could not work on Brida.

I have fixed the issues of the release I sent you. Now parameter are handled as byte[] and converted to ISO-8859-1 before passing them to Frida.

I tried this release and seems to work correctly, but I don't have a use case like yours to try. Please let me know if this build work for you.

Thank you for your help!
Federico
[Brida-0.5-jar-with-dependencies.zip](https://github.com/federicodotta/Brida/files/7447060/Brida-0.5-jar-with-dependencies.zip)

**Comment by renzyang** [comment]
Hi @federicodotta ,

I am glad to tell you that I tested with [Brida v0.5](https://github.com/federicodotta/Brida/releases/tag/v0.5) and it turns out that this version have solved this issue!!

Thanks for ur great work! 😸 👍

**Comment by federicodotta** [comment]
Hi @renzyang!

Great! Thank you for you precious help!

Federico
