### ISSUE TITLE
'Execute Method' not working

### ISSUE THREAD

**Issue by illnino** [federicodotta/Brida#9]
Hi, 

I am using Brida to investigate an android app.

After analyzing the binary, I found below two functions are responsible for encrypting and decrypting the request/response.

```
java.lang.String com.package.company.a.b(java.lang.String,java.lang.String,java.lang.String)
java.lang.String com.package.company.a.c(java.lang.String,java.lang.String,java.lang.String)
```

I had written my own functions in 'JS Editor'.
```
	encryptrequest: function(param1,param2,param3) {
		Java.perform(function(param1,param2,param3){
			//console.log(1);
			var myclass = Java.use("com.package.company.a");
			
			myclass.b.overload('java.lang.String','java.lang.String','java.lang.String').implementation=function(param1,param2,param3){
				console.log(param1);
				console.log(param2);
				console.log(param3);
				retval=this.b(param1,param2,param3);
				console.log(retval);
				return retval;
			}

		})
	},
	decryptrequest: function(param1,param2,param3) {
		Java.perform(function(param1,param2,param3){
			//console.log(1);
			var myclass = Java.use("com.package.company.a");
			
			myclass.c.overload('java.lang.String','java.lang.String','java.lang.String').implementation=function(param1,param2,param3){
				console.log(param1);
				console.log(param2);
				console.log(param3);
				retval=this.c(param1,param2,param3);
				console.log(retval);
				return retval;
				
			}

		})
	},
```

Then, I  added arguments one by one into 'Argument List' in Tab - 'Execute method'.
- plaintext
- mykey
- myiv

However, when I clicked button - 'Execute Method', I got

```
Reloading script executed  
*** Output encryptrequest:
null

```

**Comment by federicodotta** [comment]
Hi!

Your hooks are inspection hooks but are not correct for Brida. 

You can use your hooks with Frida or Brida in order to print arguments and return value of a method when the inspected method is called from the application.

If you want to call a method directly with Brida (with Execute Method or Context Menu or Custom Extension) you have to define a JS function in the Export section of Brida JS file. In your function you don't have to overload the method. You can simply take a reference to target class and then directly call target method.

For example, if your encryption method b is a static method:

```
rpc.exports = {
  encryptrequest: function(param1,param2,param3) {
    Java.perform(function() {
      var myclass = Java.use("com.package.company.a");
      return myclass.b(param1,param2,param3);
    });
  }
}
```

Let me know if this works in your situation.

Federico

**Comment by illnino** [comment]
Hi, Federicodotta

I have updated my scriptBrida.js as suggested.

```
rpc.exports = {
  encryptrequest: function(param1,param2,param3) {
    Java.perform(function() {
      var myclass = Java.use("com.package.company.a");
      return myclass.b(param1,param2,param3);
    });
  }
}
```

Then I inspected method - `com.package.company.a.b`.

When I executed the method - encryptrequest, I got below on the console. The output was still null, though the inspected method had suggested the method has been called.

```
*** entered com.package.company.a.b
Parameters:
	arg[0]: plaintext
	arg[1]: mykey
	arg[2]: myiv
*** exiting com.package.company.a.b
Return value:
	retval: cipher_text
*** Output encryptrequest:
null
```

Any idea? Did I miss anything? Thanks.

**Comment by federicodotta** [comment]
Uhm... Method "com.package.company.a.b" is a static method or an instance one?

Because if "b" method is an instance method, maybe you have to obtain a reference to an instance of that object or call the constructor of that class in order to be able to call "b", for example in this way:

```
var myclass = Java.use("com.package.company.a");
var myinstance = myclass.$new();
myinstance .b(param1,param2,param3);
```

Keep in mind that obtaining an instance of objects created by target application during runtime is not always an easy task...

Federico

**Comment by illnino** [comment]
From the decompiled code, I could see

```
public static String b(String str, String str2, String str3) {
     // encryption alg goes here
}
```

**Comment by federicodotta** [comment]
Very strange. Your configuration seems correct, the method is a static method and arguments and return value are strings.

I check again for a bug in that functionality of Brida but I haven't find on.

Can you try the execute method with another function of the same binary?

**Comment by federicodotta** [comment]
Hi ilnino,

I just checked again the "Execute method" with the last version of Frida on Android and iOS and it works.

I write you a couple of things:
1) On the BAppStore there was a wrong (old) version of Brida. Now there is the correct (new) version of Brida. Try to delete Brida and re-download it from BAppStore
2) If you edit the JavaScript file after launching the application with Brida, you have to reload the JS file using "Reload JS" button on Brida

Let me know if you can solve the problem.

Federico

**Comment by federicodotta** [comment]
I close the issue. If you need more help let me knwo and I will reopen the issue.

**Comment by mr-m0nst3r** [comment]
Hi @federicodotta ,

I met the same problem with @illnino :

Here's the rpc.exports:
```javascript
rpc.exports = {
	myenc: function(param) {
		if(Java.available){
			//return "java available"; // got ret
			Java.perform(function (){
				return "java perform"; //can't get ret
				var endec_class = Java.use("com.xxx.xxx.nativepackge.sdk.dx.TransDataEncry");
				return endec_class.encodeEncry(param); // can't get ret
			});
		}
	}	
}
```
Output:
```
*** Output myenc:
null
```

`encodeEncry` is a `static` method.

But, as I commented above, I can't get returns from `Java.perform`.

Versions:
System: MacOS latest
frida-server: 12.40
frida: 12.40
Brida: 0.3, from BAppStore

Any advice??
