### ISSUE TITLE
Getting "Error: EEXIST: file already exists, mkdir "

### ISSUE THREAD

**Issue by ganesh2183** [federicodotta/Brida#90]
Trying brida burp plugin in windows 10 environment.

Brida: Brida 0.5 pre-release 2
Node: v10.3.0
Python: 3.7.7
Frida-compile: 9

Started server, it is running successfully.Created default JS files. 
When I click on spawn application, I m getting "Error: EEXIST: file already exists, mkdir "

bridaGeneratedCompliedOutput.js file is missing inside script folder. When I try to run frida-compile.cmd to generate file, it not generating but giving file already exists error.

![16324805707631090013302762245450](https://user-images.githubusercontent.com/41476297/134662868-5be13535-3eb4-4351-a006-1a2403ce1f47.jpg)
![IMG_20210924_160656](https://user-images.githubusercontent.com/41476297/134662919-75516011-5bf0-4ba8-9f24-2cd912b9529b.jpg)

How to fix this issue.

**Comment by renzyang** [comment]
hey @ganesh2183, 

I got the same problem before. 

All you have to do is following the suggestion command in brida console, and changing the output path with a nonexistent path. Move the output file to 'Frida JS files folder', and you will find it work!

**Comment by ganesh2183** [comment]
> hey @ganesh2183,
> 
> I got the same problem before.
> 
> All you have to do is following the suggestion command in brida console, and changing the output path with a nonexistent path. Move the output file to 'Frida JS files folder', and you will find it work!

Thanks for your reply. Finally it worked.
