### ISSUE TITLE
Error: Cannot find module '/Applications/Burp Suite Community Edition.app/Contents/java/app/node'

### ISSUE THREAD

**Issue by kingcarzy** [federicodotta/Brida#91]
internal/modules/cjs/loader.js:905  throw err;  ^   
Error: Cannot find module '/Applications/Burp Suite Community Edition.app/Contents/java/app/node'  
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)  
at Function.Module._load (internal/modules/cjs/loader.js:746:27)  
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)  
at internal/main/run_main_module.js:17:47 {  
code: 'MODULE_NOT_FOUND',  
requireStack: []  
} 
 Error during frida-compile. Aborting.  

My device is Mac m1 , npm version 6.14.15 and node version 14.18.1. I have used npm version 8.0 ,  but error same .
How to solve it ? @federicodotta

**Comment by federicodotta** [comment]
Hi @kingcarzy 

you have to add node to the PATH. Refer to [this page of the Wiki](https://github.com/federicodotta/Brida/wiki/Troubleshooting) for the details.

Federico

**Comment by kingcarzy** [comment]
Thanks for your replay @federicodotta 
But I run node -v, it show version success， it already in path . you mean it neads to the /usr/bin ?

**Comment by federicodotta** [comment]
Hi @kingcarzy,

I don't have a Mac, but many Mac users reported that OSX handles paths in different ways depending on how these paths are used.

In order to fix you issue try to execute the following procedure (it is necessary to reboot after executing the launchctl command):

https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/

Federico

**Comment by kingcarzy** [comment]
Thanks@federicodotta
ok, I test a app, it has root check ,  I use script bypass check. But when I use brida spawn Appilcation ，I dont know where should the script  put or which method I should change ?

**Comment by federicodotta** [comment]
Hi @kingcarzy,

regarding on which method you should change, it depends on the particular application and requires reversing.

Regards where you should put the script, you have to load Brida default files and edit brida.js file. Refer to the Wiki for more information.

Federico
