### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by 89z** [federicodotta/Brida#92]
If I try to use this:

~~~
androidDefaultHooks.js
~~~

with this app:

~~~
com.vimeo.android.videoapp
~~~

and I start the app, it prompts for login. Alternatively you can hit SKIP in the top right corner. If I hit SKIP, I get this message:

~~~
Something strange occurred
Sorry about that. Please try again.
~~~

If I try again, same error. If I then disable proxy and try again, it works.

**Comment by federicodotta** [comment]
Hi @89z,

it is not correct to open directly  androidDefaultHooks.js. That file is compiled with others using frida-compile. Refer to the wiki for details on how use Brida.

Federico
