### ISSUE TITLE
Compile & Attach Error

### ISSUE THREAD

**Issue by mustafairan** [federicodotta/Brida#95]
Hi,
I can spawn the app with application package name (com.x.exampleapp) written in "Application ID" field using spawn button. However, when I press the Compile & Spawn, brida says that it cannot find a process with the that name. I do frida-ps and see the process name (like "my application"). So when I change  "Application ID" field with my application process name ( "my application") while the app is running , the error disappears. So I think some robustness should be added while attaching but not sure which part of the code.

**Comment by federicodotta** [comment]
Hi @mustafairan 

You need to put the application package name for "Spawn" and "Compile and Spawn" buttons and process name or PID for "Attach" and "Compile and Attach" buttons. This is the way Frida works, it is not depending on Brida itself.

Federico

**Comment by mustafairan** [comment]
Thanks for the explanation
