### ISSUE TITLE
Exception with spawn application

### ISSUE THREAD

**Issue by ccstuck** [federicodotta/Brida#96]
env:
brida0.5
macos 10.15.3

stuck:
Exception with spawn application net.razorvine.pyro.PyroException: [frida.InvalidArgumentError] script(line 2397): SyntaxError: parse error net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2813) java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) java.base/java.lang.Thread.run(Thread.java:831)

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/9977747/158010497-0ccb2ddd-e13f-44e0-8a70-eb16769b2db9.png">

**Comment by federicodotta** [comment]
Hi @ccstuck 

Due to the exception, there is a Syntax error in your JS code. You should fix it to properly start Brida. You can load default Brida code using "Create default JS files" button.

Federico
