### ISSUE TITLE
I am Getting Following Error While Using Brida

### ISSUE THREAD

**Issue by newestera** [federicodotta/Brida#97]
**** Console cleared successfully ****  

Start Pyro server command: "C:\Python310\python.exe" -i "C:\Users\xyz\AppData\Local\Temp\bridaServicePyro.py" localhost 9999  

Traceback (most recent call last):  

File "C:\Users\xyz\AppData\Local\Temp\bridaServicePyro.py", line 2, in   

import frida  

ModuleNotFoundError: No module named 'frida

**Comment by koff75** [comment]
Hi, I do have the same error, I think it could be related to a python2.7 missing installation... You should try to install python2 maybe ? 
On MacOS it seems that python2 is by now not included by default...

**Comment by federicodotta** [comment]
Hi @newestera 

Brida does not find frida module in your python environment.

You have to install frida with "pip install frida". You can also create a python virtual environment, install frida and pyro4 on it and supply the folder of the venv to Brida. Refer to the documentation for further details.

Federico
